# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Touristy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Touristy
    pod 'SnapKit'
    pod 'RxCocoa'
    pod 'RxSwift'
    pod 'Alamofire', '~> 4.3'
    pod 'SwiftyJSON'
    pod 'ObjectMapper', '~> 2.2'
    pod 'Mapbox-iOS-SDK', '~> 3.4'
    pod 'MapboxGeocoder.swift', :git => 'https://github.com/mapbox/MapboxGeocoder.swift.git', :branch => 'swift3'
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'FirebaseDatabase'
    pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :branch => 'swift3'
  # pod 'MapboxStatic.swift', :git => 'https://github.com/mapbox/MapboxStatic.swift.git', :branch => 'swift3'
   

  target 'TouristyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TouristyUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end 

